identifier_name:
  min_length:
    warning: 2
    error: 2

type_name:
  min_length:
    warning: 2
    error: 2 

line_length:
  warning: 160
  error: 200
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true

file_length:
  warning: 700
  error: 800

cyclomatic_complexity:
  warning: 15
  error: 60

function_body_length:
  warning: 250
  error: 300

type_body_length:
  warning: 600
  error: 800